### ISSUE TITLE
Correct structure

### ISSUE THREAD

**Issue by akashnimare** [unindented/grunt-electron-debian-installer#1]
Hey I was trying to build .deb but it's not working. Here is my dir structure

```
path/to/myapp/
├── LICENSE
├── index.js
├── browser.js
├── browser.css
├── menu.js
├── Gruntfile.js
├── node_modules
│   ├── fs
│   └── yargs
├── package.json
└── icon.png
```

Gruntfile.js

```

module.exports = function(grunt) {

  // Project configuration.
  grunt.initConfig({
    pkg: grunt.file.readJSON('package.json'),
    'electron-debian-installer': {
    myapp: {
    options: {
      arch: 'amd64'
    },
    src: 'absoulute/path/of/myapp/',
    dest: 'absoulute/path/of/myapp/linux64/'
  }
}
  });
  grunt.loadNpmTasks('grunt-electron-debian-installer');
   grunt.registerTask('default', ['electron-debian-installer']);
};

```

Is it correct?

**Comment by unindented** [comment]
Have you built your app with something like [`electron-packager`](https://github.com/maxogden/electron-packager) first? The `grunt-electron-debian-installer` just packages an already built app as a `.deb` package, but it doesn't build the project itself.

Let me know

**Comment by akashnimare** [comment]
Oh I thought it builds the project itself. Btw I am trying to build .deb for [this](https://github.com/sindresorhus/caprine). Can you tell me how should I build a .deb for this? I am having a hard time converting it to .deb.

**Comment by unindented** [comment]
@akashnimare You just need to run the `electron-packager` task: https://github.com/sindresorhus/caprine/blob/28fee9c72d5c3a356dfdfd106a3f98a498aaf09d/package.json#L22

And then point `grunt-electron-debian-installer` to the destination folder, which seems to be `dist/Caprine-linux-x64/`.

Let me know how it goes.
